data:
  obs_datapath: '/home/wch/Gaussian-Process-Approximation/official_experiment/bin_df.pkl'
  test_data_path: '/home/wch/Gaussian-Process-Approximation/official_experiment/test_loc.csv'
device: 'cuda:1'
model:
  name: 'DeepSpatiotemporalGPNN'  # Options: 'DeepSpatiotemporalGPNN', 'DeepMaternRandomPhaseS2RFFNN'.....
  num_layers: 6
  hidden_dim: 1000
  bottleneck_dim: 128
  output_dim: 1
  spatial_layer_type: 'Matern'  # Options: 'Matern', 'SquaredExponential', etc.....
  temporal_layer_type: 'Matern'
  kwargs: {}  # Additional arguments for the model if needed...
bayesian_optimization:
  n_iterations: 10
  initial_samples: 10
  bounds:
    - [0.1, 10]  # spatial_lengthscale
    - [0.1, 10]  # temporal_lengthscale
    - [0.1, 1]   # amplitude
  optimize_observation_noise: True  # Flag to enable/disable observation noise optimization
  observation_noise_bounds: [0.00001, 0.01]
  penalty_weight: 0.9
uq_method:
  type: 'deep_ensemble'  # Options: 'deep_ensemble', 'mc_dropout'.....
training:
  num_epochs: 1
  batch_size: 1024
  learning_rate: 0.001
  num_models: 10
results:
  csv_filename: '/home/wch/rebuttal/DeepRandomFeatures/rebuttal_results/2nd_rebuttal/hyperparams_nll_30.csv'
  predictions_filename: '/home/wch/rebuttal/DeepRandomFeatures/rebuttal_results/2nd_rebuttal/final_predictions_30.pt'
  variance_filename: '/home/wch/rebuttal/DeepRandomFeatures/rebuttal_results/2nd_rebuttal/final_variance_30.pt'
  individual_predictions_filename: '/home/wch/rebuttal/DeepRandomFeatures/rebuttal_results/2nd_rebuttal/individual_final_predictions_spherical.pt'
